name: CI
on:
- push
- pull_request
jobs:

  main:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        include:
        - python: '3.6'
          os: ubuntu-20.04
        - python: '3.7'
          os: ubuntu-20.04
        - python: '3.8'
          os: ubuntu-20.04
        - python: '3.9'
          os: ubuntu-20.04
        - python: '3.10'
          os: ubuntu-22.04
        - python: '3.11'
          os: ubuntu-22.04
        - python: '3.12'
          os: ubuntu-22.04
        - python: '3.13'
          os: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - name: set up Python ${{matrix.python}}
      uses: actions/setup-python@v5
      with:
        python-version: ${{matrix.python}}
    - name: run tests
      run: |
        prove -v
    - name: Mastodon network test
      run: |
        ./zygolophodon https://infosec.exchange/@lcamtuf/109537142030669006
    - name: Pleroma network test
      run: |
        ./zygolophodon https://pleroma.debian.social/notice/ApspySbhKOv7MAQZPM
    - name: install
      run: |
        make install PREFIX=~/.local
    - name: post-install smoke-test
      run: |
        cd /
        zygolophodon --version
    - name: run pydiatra
      run: |
        python3 -m pip install pydiatra
        python3 -m pydiatra -v .
    - name: run pyflakes
      run: |
        python3 -m pip install pyflakes
        python3 -m pyflakes .
    - name: run pylint
      run: |
        python3 -m pip install pylint
        python3 -m pylint zygolophodon
    - name: check README syntax
      run: |
        python3 -m pip install restructuredtext-lint pygments
        rst-lint --level=info --encoding=UTF-8 README

  nonpython:
    strategy:
      matrix:
        os:
        - ubuntu-20.04
        - ubuntu-22.04
        - ubuntu-24.04
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v4
    - name: set up APT
      run: |
        printf 'Apt::Install-Recommends "false";\n' | sudo tee -a /etc/apt/apt.conf
        sudo apt-get update
    - name: install perlcritic
      run: |
        sudo apt-get install libperl-critic-perl
    - name: run perlcritic
      run: |
        perlcritic $(grep -rl '/env perl$' .)
    - name: regenerate README
      run: |
        private/update-readme
        git diff --exit-code

# vim:ts=2 sts=2 sw=2 et
